var playerInstance = jwplayer("myElement");
playerInstance.setup({
    hlshtml: true,

    playlist: [{
        file: "http://users.metropolia.fi/~neahu/music/Cyranoi - Abiogenesis.mp3",
        image: "exist.jpg",
        title: "Cyranoi - Abiogenesis",
        description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 1 | Duration: 4:45</h6><br><br><br><p>Radiant, scalding hot, nothingness. <br>From a gleam in the void, spark this life, spark this life, thus it has begun! <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br>Collision of titans in the ages before it all. <br>Combine, unite, together something bigger, something stronger. <br>Progenitor, prime mover, set this obscurity, ablaze. <br>Give the needs to survive, set your hands upon the sky. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br><br>Generating growth, in these depths. <br>From these oh so very dim depths, arise. <br>Ascend and claim your place, ascend and face these threats. <br><br>Born from the flames of Hadean, so small in the eyes of existence. <br>But to know what is ahead, so the world, the world is now scared. <br>From chaos you were born, and chaos you will cause. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>(Blank sheet for a painter!) <br>This soil you walk upon, is not foregone conclusion. <br>(Piece of paper for an author!) <br><br>What were the odds, oblivious minds wake up! <br>What were the odds, what were the odds, <br>Oblivious minds wake up, wake up, now!</p>'

    },
    {
        file: "http://users.metropolia.fi/~neahu/music/Cyranoi - Pioneers.mp3",
        image: "exist.jpg",
        title: "Cyranoi - Pioneers",
        description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 2 | Duration: 4:18</h6><br><br><br><p>And so, they walk on. <br>Eyes wide open, hands are closed. <br>Ready for anything. <br>Storming into the uncharted, unfamiliar. <br>No knowledge of, the dangers they will face. <br>Go forth, don not fear. <br>Whatever lies ahead, is nothing you can not bear. <br><br>The frontiers wait, untouched and wild. <br>Stretch your legs and take a step ahead. <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br>Forever grateful for the sacrifices they made, they gave. <br>All, they, could, to make a better life for us. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br><br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br><br>Descendants <br>Now let us sing for them! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br>Treading the ground for us. <br><br>You were there the day I was born! <br>You were there the day when could not take the weight of the world! <br>And I will miss you, the day when you are gone! <br>I will remember, every life lesson that you told me! <br>I will remember, how you helped me here! <br><br>Thus they built the foundation. <br>For us to carry on the work that they had done. <br>As a legacy, they gave it to us. <br>And the knowledge, will forever pass on! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave!</p>'
    },
    {
        file: "http://users.metropolia.fi/~neahu/music/Cyranoi - Flesh And Mind (ft. Sithu Aye).mp3", 
        image:"exist.jpg", 
        title: "Flesh And Mind (ft. Sithu Aye)",
        description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 3 | Duration: 4:16</h6><br><br><br><p>Advanced, supreme beings, nothing stands in their way, stands in their way. <br>Numbers, calculations and building massive machines, massive machines. <br>So overpowered, so selfish. <br>The rivers in their chests are tainted by the beast. <br><br>The rebirth of compassion lies within anyone of us. <br>So light the flame that has been dead for far too long. <br><br>Look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you, in front of you! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down. <br><br>All of this, all of this will go to waste. <br>If we don not kill the beast. <br><br>So look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you! <br>So take a look around, watch your surroundings. <br>The beauty is everywhere, it is within you! <br><br>The only way, you can make a change! <br>Is understanding that change has to be made! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down to our demise. <br>To our own demise. <br><br>Is it too late to change? <br>Can the difference be made, anymore?</p>'
    },
    {
        file: "http://users.metropolia.fi/~neahu/music/Cyranoi - Avarice.mp3", 
        image:"exist.jpg", 
        title: "Avarice",
        description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 4 | Duration: 5:49</h6><br><br><br><p>Pull the roots from the ground, turn the green into grey. <br>Trees fall but they wont grow no more. <br>Kill every living thing, so it is only you who is left. <br>They wont come back from the dead. <br>Toxic rivers flow, spreading the sickness. <br>The madness has taken over. <br><br>I am burning, I am burning from inside. <br>I gave you a home, and now you are killing me! <br>You are killing me! <br><br>No more clear sky, no more fresh air. <br>You have dug your own grave. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Your machines can not help you now, your buildings will fall to the ground. <br><br>The mountains shoot flames and ground is covered in ashes. <br>This ends like it began. <br><br>Like the writings on the beach, the flames will wash you away. Away. <br>Like the writings on the beach, the flames will wash you away. <br>Like the writings on the beach. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Like the writings on the beach, the flames will wash you away. <br><br>Even though, we know the outcome.<br>Even though, we see our future. <br><br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>Forests have burned down, lakes have dried out.<br>Birds do not sing no more. <br><br>It was so long impending, you closed your eyes from it. <br>You can not prevent this, your chances are gone. <br><br>Even though, we know the outcome. <br>(We close our eyes we cover our ears) <br>Even though, we see our future. <br>(We tell ourselves it is fine we believe in lies) <br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>I am become death, destroyer of the worlds. <br>This was long to come...</p>'
    },
    {
        file: "http://users.metropolia.fi/~neahu/music/Cyranoi - Event Horizon (ft. Niklas Turunen).mp3", 
        image:"exist.jpg", 
        title: "Event Horizon (ft. Niklas Turunen)",
        description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 5 | Duration: 5:55</h6><br><br><br><p>Grasp, in front of the dark ages.<br> Red, circle surrounds us. <br>Fire, shooting from the underworld. <br>Light, so bright blinds your eyes.<br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>It was written in stone, so this should not be a surprise. <br>The signs were shown. <br><br>All the mistakes, every wrong turn. <br>Journey so long, was it all for nothing? <br>All the mistakes, every wrong turn. <br>Journey so long, but in the stars so short (so short!). <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home. <br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>Floating quietly, into mist of ambiguity. <br>The end is so warm, so inviting, let it take you. <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home.<br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>All these beautiful souls. <br>Oh such peaceful kinds. <br>Their all now wiped away. <br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>All this time, we wasted away our lives. <br>Now we stand here, with brand new eyes.</p>'
    }
    ]
});

//valmiit playlistit molemmille EP
var playlistEP1 = [{
    "file":"http://users.metropolia.fi/~neahu/music/Cyranoi - Abiogenesis.mp3", 
    "image":"exist.jpg", 
    "title": "Abiogenesis",
    "description":'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 1 | Duration: 4:45</h6><br><br><br><p>Radiant, scalding hot, nothingness. <br>From a gleam in the void, spark this life, spark this life, thus it has begun! <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br>Collision of titans in the ages before it all. <br>Combine, unite, together something bigger, something stronger. <br>Progenitor, prime mover, set this obscurity, ablaze. <br>Give the needs to survive, set your hands upon the sky. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br><br>Generating growth, in these depths. <br>From these oh so very dim depths, arise. <br>Ascend and claim your place, ascend and face these threats. <br><br>Born from the flames of Hadean, so small in the eyes of existence. <br>But to know what is ahead, so the world, the world is now scared. <br>From chaos you were born, and chaos you will cause. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>(Blank sheet for a painter!) <br>This soil you walk upon, is not foregone conclusion. <br>(Piece of paper for an author!) <br><br>What were the odds, oblivious minds wake up! <br>What were the odds, what were the odds, <br>Oblivious minds wake up, wake up, now!</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Pioneers.mp3", 
    "image": "exist.jpg", 
    "title": "Pioneers",
    "description":'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 2 | Duration: 4:18</h6><br><br><br><p>And so, they walk on. <br>Eyes wide open, hands are closed. <br>Ready for anything. <br>Storming into the uncharted, unfamiliar. <br>No knowledge of, the dangers they will face. <br>Go forth, don not fear. <br>Whatever lies ahead, is nothing you can not bear. <br><br>The frontiers wait, untouched and wild. <br>Stretch your legs and take a step ahead. <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br>Forever grateful for the sacrifices they made, they gave. <br>All, they, could, to make a better life for us. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br><br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br><br>Descendants <br>Now let us sing for them! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br>Treading the ground for us. <br><br>You were there the day I was born! <br>You were there the day when could not take the weight of the world! <br>And I will miss you, the day when you are gone! <br>I will remember, every life lesson that you told me! <br>I will remember, how you helped me here! <br><br>Thus they built the foundation. <br>For us to carry on the work that they had done. <br>As a legacy, they gave it to us. <br>And the knowledge, will forever pass on! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave!</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Flesh And Mind (ft. Sithu Aye).mp3", 
    "image":"exist.jpg", 
    "title": "Flesh And Mind (ft. Sithu Aye)",
    "description":'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 3 | Duration: 4:16</h6><br><br><br><p>Advanced, supreme beings, nothing stands in their way, stands in their way. <br>Numbers, calculations and building massive machines, massive machines. <br>So overpowered, so selfish. <br>The rivers in their chests are tainted by the beast. <br><br>The rebirth of compassion lies within anyone of us. <br>So light the flame that has been dead for far too long. <br><br>Look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you, in front of you! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down. <br><br>All of this, all of this will go to waste. <br>If we don not kill the beast. <br><br>So look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you! <br>So take a look around, watch your surroundings. <br>The beauty is everywhere, it is within you! <br><br>The only way, you can make a change! <br>Is understanding that change has to be made! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down to our demise. <br>To our own demise. <br><br>Is it too late to change? <br>Can the difference be made, anymore?</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Avarice.mp3", 
    "image":"exist.jpg", 
    "title": "Avarice",
    "description":'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 4 | Duration: 5:49</h6><br><br><br><p>Pull the roots from the ground, turn the green into grey. <br>Trees fall but they wont grow no more. <br>Kill every living thing, so it is only you who is left. <br>They wont come back from the dead. <br>Toxic rivers flow, spreading the sickness. <br>The madness has taken over. <br><br>I am burning, I am burning from inside. <br>I gave you a home, and now you are killing me! <br>You are killing me! <br><br>No more clear sky, no more fresh air. <br>You have dug your own grave. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Your machines can not help you now, your buildings will fall to the ground. <br><br>The mountains shoot flames and ground is covered in ashes. <br>This ends like it began. <br><br>Like the writings on the beach, the flames will wash you away. Away. <br>Like the writings on the beach, the flames will wash you away. <br>Like the writings on the beach. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Like the writings on the beach, the flames will wash you away. <br><br>Even though, we know the outcome.<br>Even though, we see our future. <br><br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>Forests have burned down, lakes have dried out.<br>Birds do not sing no more. <br><br>It was so long impending, you closed your eyes from it. <br>You can not prevent this, your chances are gone. <br><br>Even though, we know the outcome. <br>(We close our eyes we cover our ears) <br>Even though, we see our future. <br>(We tell ourselves it is fine we believe in lies) <br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>I am become death, destroyer of the worlds. <br>This was long to come...</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Event Horizon (ft. Niklas Turunen).mp3", 
    "image":"exist.jpg", 
    "title": "Event Horizon (ft. Niklas Turunen)",
    "description":'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 5 | Duration: 5:55</h6><br><br><br><p>Grasp, in front of the dark ages.<br> Red, circle surrounds us. <br>Fire, shooting from the underworld. <br>Light, so bright blinds your eyes.<br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>It was written in stone, so this should not be a surprise. <br>The signs were shown. <br><br>All the mistakes, every wrong turn. <br>Journey so long, was it all for nothing? <br>All the mistakes, every wrong turn. <br>Journey so long, but in the stars so short (so short!). <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home. <br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>Floating quietly, into mist of ambiguity. <br>The end is so warm, so inviting, let it take you. <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home.<br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>All these beautiful souls. <br>Oh such peaceful kinds. <br>Their all now wiped away. <br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>All this time, we wasted away our lives. <br>Now we stand here, with brand new eyes.</p>'
    }];

var playlistEP2 = [{
    "file":"http://users.metropolia.fi/~neahu/music/Cyranoi - Within Understanding Lies Acceptance.mp3", 
    "image":"challengerdeep.jpg", 
    "title": "Within Understanding Lies Acceptance",
    "description":'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 1 | Duration: 3:30</h6><br><br><br><p>[Instrumental]</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Challenger Deep.mp3", 
    "image": "challengerdeep.jpg", 
    "title": "Challenger Deep",
    "description":'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 2 | Duration: 3:27</h6><br><br><br><p>In the darkness you lay and you turn into grey<br>Repetitious life is your cage, you feel you cant run away<br><br>Everyday you walk the streets and bow your head down<br>And ask yourself, why am I here, there is no reason to stay<br><br>It is all hell for me, please help me I need, someone, or I am done!<br><br>Am I just a ghost, can no one hear me?<br>Am I irrelevant, is this really how it is?<br><br>This road we go is full of stones, so please just hold on<br>Take my word it is worth in the long run<br><br>This world will fuck you up if you don not stand and fight for your life<br>Stand and fight for your life<br><br>I keep drowning and drowning, I can not breath<br>With the last bit of strength, I reach my hand<br><br>I take a hold of what I have, I wont give it away<br>No no, not so easy, hey this time I will stand<br><br>Be the light in your life<br>This hell will surely pass by<br>Just keep your eyes peeled, stay steady<br><br>When we fall, down we fall, take a grip, and hold<br>These demons don not control your life<br>When we fall, down we fall, take a grip, and hold<br>Find your light and don not let go.<br><br>These tidal waves, your demons shattering<br>Your ship is constantly being hit by these<br>But remember this, whatever gets your way<br>Smooth seas don not make good sailors<br><br>When we fall, down we fall, take a grip, and hold<br>These demons do not control your life<br>When we fall, down we fall, take a grip, and hold<br>Find your light and do not let go<br> Do not let go, do not let go, never ever let go<br>These tidal waves, these tidal waves <br>You are stronger than them they wont wash you away</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Lucid Dream.mp3", 
    "image": "challengerdeep.jpg", 
    "title": "Lucid Dream",
    "description":'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 3 | Duration: 4:44</h6><br><br><br><p>Time, present, past and the future<br>Creation of human mind<br>Give up all you think you know, for it is all just a theory<br>Without bias, give your mind to reality<br>Past is gone? No, past is now<br>We are living it all in this moment<br>We are in the future, we are in the past.<br><br>And still we are living it all now <br>Everything is happening right now <br>Causality, relativity<br>Existence, fact or fiction?<br>Causality, relativity<br>Existence, fact or fiction?<br><br>You are objectively real, real!<br>You are a theory, a theory!<br>A product of human mind<br><br>Pondering, pondering, our whole existence<br>Questioning, questioning, this so called truth<br>What if it is all a dream, what if it is all in my head?<br>Pondering, pondering, our whole existence<br><br>We will always search for answers<br>Veritas vos liberabit<br>It is a burning heat under our skin<br>We have to know where we came from<br>We have to know, we have to know, we have to know!<br>What brought us here?<br>The truth, give us the truth!<br>Causality, relativity<br>Existence, fact or fiction?<br>Causality, relativity<br>Existence, fact or fiction?<br><br>Is there even such thing as freewill?<br>Or has someone already planned it all out?<br><br>You are objectively real, real! <br>You are a theory, a theory!<br>A product of human mind<br><br>Pondering, pondering, our whole existence<br>Questioning, questioning, this so called truth<br>What if it is all a dream, what if it is all in my head?<br>Pondering, pondering, our whole existence<br><br>But the hand only moves in one way<br>Pondering wont help, live it now or never!</p>'
    },
    {
    "file": "http://users.metropolia.fi/~neahu/music/Cyranoi - Another Sun To Embrace Us.mp3", 
    "image": "challengerdeep.jpg", 
    "title": "Another Sun To Embrace Us",
    "description":'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 4 | Duration: 4:25</h6><br><br><br><p>[Instrumental]</p>'
    }];
    
//lataa playlistin soittimeen kun painettu kuvaa
    function loadPlaylist(thePlaylist) {
        jwplayer('myElement').load(thePlaylist)
        jwplayer().play();
    }

//--nea säätää että biisit soi --//
//-- tämä functio lisää uuden biisin soittolistaan --//
function addMusic(fileName, imageName, titleName, descriptionName) {
    var playlist = jwplayer().getPlaylist();
    var newItem = {
        file: fileName,
        image: imageName,
        title: titleName,
        description: descriptionName
    };
    playlist.push(newItem);
    jwplayer().load(playlist);
        console.log(newItem.title);
           document.getElementById("playlist").innerHTML += '<p>' + newItem.title +'</p>';
       
        
    //tällä saa consolissa näkymään lisättyjen biisien nimet
    //console.log(newItem.title);
}
//document.getElementById("playlist").innerHTML = newItem.title;
//-- tämä functio lisää uuden biisin soittolistaan --//

//tämä on se functio jonka avulla biisit lähtee soimaan//
function playThisVideo(fileName, imageName, titleName, descriptionName) { 
    jwplayer('myElement').load([{ file: fileName, image: imageName, title: titleName, description: descriptionName }]); jwplayer().play(); }
//tämä on se functio jonka avulla biisit lähtee soimaan//

//tässä biisit tungetaan jwplayerin tietoisuuteen kuvan kanssa ja että ei ala soimaan auto

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Abiogenesis.mp3',
image: 'exist.jpg',
title: 'Abiogenesis',
description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 1 | Duration: 4:45</h6><br><br><br><p>Radiant, scalding hot, nothingness. <br>From a gleam in the void, spark this life, spark this life, thus it has begun! <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br>Collision of titans in the ages before it all. <br>Combine, unite, together something bigger, something stronger. <br>Progenitor, prime mover, set this obscurity, ablaze. <br>Give the needs to survive, set your hands upon the sky. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>Blank sheet for a painter! <br>Piece of paper for an author! <br>Embrace this blessing! <br>Embrace this moment! <br><br>Generating growth, in these depths. <br>From these oh so very dim depths, arise. <br>Ascend and claim your place, ascend and face these threats. <br><br>Born from the flames of Hadean, so small in the eyes of existence. <br>But to know what is ahead, so the world, the world is now scared. <br>From chaos you were born, and chaos you will cause. <br><br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>Blank sheet for a painter, for a painter! <br>Piece of paper for, for an author. <br>This soil you walk upon, is not foregone conclusion. <br>(Blank sheet for a painter!) <br>This soil you walk upon, is not foregone conclusion. <br>(Piece of paper for an author!) <br><br>What were the odds, oblivious minds wake up! <br>What were the odds, what were the odds, <br>Oblivious minds wake up, wake up, now!</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Pioneers.mp3',
image: 'exist.jpg',
title: 'Pioneers',
description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 2 | Duration: 4:18</h6><br><br><br><p>And so, they walk on. <br>Eyes wide open, hands are closed. <br>Ready for anything. <br>Storming into the uncharted, unfamiliar. <br>No knowledge of, the dangers they will face. <br>Go forth, don not fear. <br>Whatever lies ahead, is nothing you can not bear. <br><br>The frontiers wait, untouched and wild. <br>Stretch your legs and take a step ahead. <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br>Forever grateful for the sacrifices they made, they gave. <br>All, they, could, to make a better life for us. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br><br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave! <br><br>Descendants <br>Now let us sing for them! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br>Treading the ground for us. <br><br>You were there the day I was born! <br>You were there the day when could not take the weight of the world! <br>And I will miss you, the day when you are gone! <br>I will remember, every life lesson that you told me! <br>I will remember, how you helped me here! <br><br>Thus they built the foundation. <br>For us to carry on the work that they had done. <br>As a legacy, they gave it to us. <br>And the knowledge, will forever pass on! <br><br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they carried us and they held our hands. <br>Where we would be without them, show reverence. <br>Pioneers, they gave us strength and they stood by us. <br>Where we would be without them, show reverence. <br>Generation after generation, look to them for guidance. <br>Pioneers, treading the ground for those, who follow behind. <br><br>Valiant, lion-hearted. <br>Our carriers. (Carry us) <br>Through this mist of grey. <br>Our guardians! <br>They built the roads, they took the risks. <br>It was all for us, from cradle to the grave!</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Flesh And Mind (ft. Sithu Aye).mp3',
image: 'exist.jpg',
title: 'Flesh And Mind (ft. Sithu Aye)',
description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 3 | Duration: 4:16</h6><br><br><br><p>Advanced, supreme beings, nothing stands in their way, stands in their way. <br>Numbers, calculations and building massive machines, massive machines. <br>So overpowered, so selfish. <br>The rivers in their chests are tainted by the beast. <br><br>The rebirth of compassion lies within anyone of us. <br>So light the flame that has been dead for far too long. <br><br>Look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you, in front of you! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down. <br><br>All of this, all of this will go to waste. <br>If we don not kill the beast. <br><br>So look carefully, keep your eyes open wide. <br>See the beauty that lies in front of you! <br>So take a look around, watch your surroundings. <br>The beauty is everywhere, it is within you! <br><br>The only way, you can make a change! <br>Is understanding that change has to be made! <br><br>The gift that once was given to us. <br>It must not go in vain, we can not waste it away, forever keeping the flame. <br>Stop the bleeding, kill the plague, do not segregate. <br>If this goes on, lust will pull us down to our demise. <br>To our own demise. <br><br>Is it too late to change? <br>Can the difference be made, anymore?</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Avarice.mp3',
image: 'exist.jpg',
title: 'Avarice',
description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 4 | Duration: 5:49</h6><br><br><br><p>Pull the roots from the ground, turn the green into grey. <br>Trees fall but they wont grow no more. <br>Kill every living thing, so it is only you who is left. <br>They wont come back from the dead. <br>Toxic rivers flow, spreading the sickness. <br>The madness has taken over. <br><br>I am burning, I am burning from inside. <br>I gave you a home, and now you are killing me! <br>You are killing me! <br><br>No more clear sky, no more fresh air. <br>You have dug your own grave. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Your machines can not help you now, your buildings will fall to the ground. <br><br>The mountains shoot flames and ground is covered in ashes. <br>This ends like it began. <br><br>Like the writings on the beach, the flames will wash you away. Away. <br>Like the writings on the beach, the flames will wash you away. <br>Like the writings on the beach. <br><br>As the embers fall, you know that soon it is all gone. <br>The clouds are spitting poison, your lungs are breathing sulfur. <br>Like the writings on the beach, the flames will wash you away. <br><br>Even though, we know the outcome.<br>Even though, we see our future. <br><br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>Forests have burned down, lakes have dried out.<br>Birds do not sing no more. <br><br>It was so long impending, you closed your eyes from it. <br>You can not prevent this, your chances are gone. <br><br>Even though, we know the outcome. <br>(We close our eyes we cover our ears) <br>Even though, we see our future. <br>(We tell ourselves it is fine we believe in lies) <br>It wont make us stop. <br>It will not make us realize. <br>What we have done, we have, set our home on fire. <br>What will you do when it is all gone? <br>Where will you go? <br><br>I am become death, destroyer of the worlds. <br>This was long to come...</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Event Horizon (ft. Niklas Turunen).mp3',
image: 'exist.jpg',
title: 'Event Horizon (ft. Niklas Turunen)',
description:'<h6>Album: Exist (EP) <br>Year: 2016 | Track no: 5 | Duration: 5:55</h6><br><br><br><p>Grasp, in front of the dark ages.<br> Red, circle surrounds us. <br>Fire, shooting from the underworld. <br>Light, so bright blinds your eyes.<br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>It was written in stone, so this should not be a surprise. <br>The signs were shown. <br><br>All the mistakes, every wrong turn. <br>Journey so long, was it all for nothing? <br>All the mistakes, every wrong turn. <br>Journey so long, but in the stars so short (so short!). <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home. <br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>Floating quietly, into mist of ambiguity. <br>The end is so warm, so inviting, let it take you. <br><br>What lies beyond, the boundaries that we can not see. <br>The world that no mortal can see. <br><br>It is a mystery, forever secrecy. <br>Something that just can not be revealed. <br>For someone who still walks and breathes. <br><br>We have reached the point of no return, we can not go back home.<br>We can not because it is gone. <br><br>The valleys and the waterfalls, the oceans and the mountains. <br>It is all now history, left only a memory. <br>Now everywhere you look, you will see the life that you took. <br>The ghost, the shadow, of a life once so hallowed. <br><br>So hallowed, so sacred. <br>All these beautiful souls. <br>Oh such peaceful kinds. <br>Their all now wiped away. <br><br>Adrift in a void, looking for the answers. <br>Seeing only blank space, flowing into darkness. <br><br>All this time, we wasted away our lives. <br>Now we stand here, with brand new eyes.</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Within Understanding Lies Acceptance.mp3',
image: 'challengerdeep.jpg',
title:'Within Understanding Lies Acceptance',
description:'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 1 | Duration: 3:30</h6><br><br><br><p>[Instrumental]</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Challenger Deep.mp3', 
image: 'challengerdeep.jpg',
title: 'Challenger Deep',
description:'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 2 | Duration: 3:27</h6><br><br><br><p>In the darkness you lay and you turn into grey<br>Repetitious life is your cage, you feel you cant run away<br><br>Everyday you walk the streets and bow your head down<br>And ask yourself, why am I here, there is no reason to stay<br><br>It is all hell for me, please help me I need, someone, or I am done!<br><br>Am I just a ghost, can no one hear me?<br>Am I irrelevant, is this really how it is?<br><br>This road we go is full of stones, so please just hold on<br>Take my word it is worth in the long run<br><br>This world will fuck you up if you don not stand and fight for your life<br>Stand and fight for your life<br><br>I keep drowning and drowning, I can not breath<br>With the last bit of strength, I reach my hand<br><br>I take a hold of what I have, I wont give it away<br>No no, not so easy, hey this time I will stand<br><br>Be the light in your life<br>This hell will surely pass by<br>Just keep your eyes peeled, stay steady<br><br>When we fall, down we fall, take a grip, and hold<br>These demons don not control your life<br>When we fall, down we fall, take a grip, and hold<br>Find your light and don not let go.<br><br>These tidal waves, your demons shattering<br>Your ship is constantly being hit by these<br>But remember this, whatever gets your way<br>Smooth seas don not make good sailors<br><br>When we fall, down we fall, take a grip, and hold<br>These demons do not control your life<br>When we fall, down we fall, take a grip, and hold<br>Find your light and do not let go<br> Do not let go, do not let go, never ever let go<br>These tidal waves, these tidal waves <br>You are stronger than them they wont wash you away</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Lucid Dream.mp3',
image: 'challengerdeep.jpg',
title: 'Lucid Dream',
description:'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 3 | Duration: 4:44</h6><br><br><br><p>Time, present, past and the future<br>Creation of human mind<br>Give up all you think you know, for it is all just a theory<br>Without bias, give your mind to reality<br>Past is gone? No, past is now<br>We are living it all in this moment<br>We are in the future, we are in the past.<br><br>And still we are living it all now <br>Everything is happening right now <br>Causality, relativity<br>Existence, fact or fiction?<br>Causality, relativity<br>Existence, fact or fiction?<br><br>You are objectively real, real!<br>You are a theory, a theory!<br>A product of human mind<br><br>Pondering, pondering, our whole existence<br>Questioning, questioning, this so called truth<br>What if it is all a dream, what if it is all in my head?<br>Pondering, pondering, our whole existence<br><br>We will always search for answers<br>Veritas vos liberabit<br>It is a burning heat under our skin<br>We have to know where we came from<br>We have to know, we have to know, we have to know!<br>What brought us here?<br>The truth, give us the truth!<br>Causality, relativity<br>Existence, fact or fiction?<br>Causality, relativity<br>Existence, fact or fiction?<br><br>Is there even such thing as freewill?<br>Or has someone already planned it all out?<br><br>You are objectively real, real! <br>You are a theory, a theory!<br>A product of human mind<br><br>Pondering, pondering, our whole existence<br>Questioning, questioning, this so called truth<br>What if it is all a dream, what if it is all in my head?<br>Pondering, pondering, our whole existence<br><br>But the hand only moves in one way<br>Pondering wont help, live it now or never!</p>',
autostart: false });

jwplayer('myElement').setup({ file: 'http://users.metropolia.fi/~neahu/music/Cyranoi - Another Sun To Embrace Us.mp3',
image: 'challengerdeep.jpg',
title: 'Another Sun To Embrace Us', 
description:'<h6>Album: Challenger Deep (EP) <br>Year: 2015 | Track no: 4 | Duration: 4:25</h6><br><br><br><p>[Instrumental]</p>',
autostart: false });
//--nea säätää että biisit soi --//

// -- https://stackoverflow.com/questions/17220793/jwplayer-append-file-to-playlist --//
